packages:
  - "."
  - ".dependencies/vega"
  - ".dependencies/vega/packages/protocol"
  - ".dependencies/vega-plugin-richtext"

linkWorkspacePackages: true
autoInstallPeers: false
strictPeerDependencies: true
engineStrict: true

allowBuilds:
  esbuild: true
